#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'migratoryBirds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def migratoryBirds(arr):
    maxi=arr[0]
    count_m=arr.count(arr[0])
    for i in arr:
        if(arr.count(i)>count_m):
            maxi=i
            count_m=arr.count(maxi)
        elif(arr.count(i)==count_m):
            if(i<maxi):
                maxi=i
                count_m=arr.count(maxi)
            else:
                maxi=maxi
        arr=list(filter((i).__ne__,arr))
    return maxi

    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
